### ISSUE TITLE
在vue2 组件里，导入时，找不到模块。

### ISSUE THREAD

**Issue by codejc** [MopTym/vue-waterfall#31]
package.json 里已经有该模块的依赖了。

**Comment by ontheway1215** [comment]
在nuxt中遇到同样问题，第一次能正常运行，瀑布流也能出来，但是重新npm run dev后会报错误
[vue-router] Failed to resolve async component default: Error: Cannot find module 'vue-waterfall/lib/waterfall' from '/Users/bqmm-yjm/Desktop/file/node/dong2'
[vue-router] uncaught error during route navigation:
{ Error: Cannot find module 'vue-waterfall/lib/waterfall' from '/Users/bqmm-yjm/Desktop/file/node/dong2'
    at Function.module.exports [as sync] (/Users/bqmm-yjm/Desktop/file/node/dong2/node_modules/resolve/lib/sync.js:40:15)
    at r (/Users/bqmm-yjm/Desktop/file/node/dong2/node_modules/vue-server-renderer/build.js:5814:44)
    at Object.<anonymous> (server-bundle.js:2533:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.80 (0.server-bundle.js:406:86)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.69 (0.server-bundle.js:64:3)
    at __webpack_require__ (server-bundle.js:27:30)
    at <anonymous> code: 'MODULE_NOT_FOUND' }

**Comment by PatrickSR** [comment]
有解决方案吗？

**Comment by rlam3** [comment]
@ontheway1215 @PatrickSR  were you able to get this working with nuxt? if so could you please share the codebase? Thanks!

**Comment by xmqywx** [comment]
@rlam3 #33
